name: type_helper
description: TypeHelper, a more capable user-written Type
version: 1.0.0
repository: https://github.com/eernstg/type_helper

environment:
  sdk: ^3.4.0-250.0.dev

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
