name: typer
description: Typer, a more capable version of Type
version: 1.0.0
repository: https://github.com/eernstg/typer

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
