name: typer
description: >-
  Provide `Typer`, a more capable version of `Type`.
  Supports relational operators, type tests and casts,
  a limited form of existential open, and promotion.
version: 1.0.7
repository: https://github.com/eernstg/typer

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
